import Trip from "../models/Trip.js";

/**
 * ✅ Save Trip to DB
 * (after itinerary is generated by Gemini)
 */
export const saveTrip = async (req, res, next) => {
  try {
    // Attach user id to trip data
    const trip = await Trip.create({ ...req.body, userId: req.user.id });
    res.json({
      success: true,
      message: "Trip saved successfully ✅",
      data: trip
    });
  } catch (err) {
    console.error("❌ Error saving trip:", err);
    res.status(500).json({ error: "Failed to save trip" });
  }
};

/**
 * ✅ Get all trips saved by logged-in user
 */
export const myTrips = async (req, res, next) => {
  try {
    const trips = await Trip.find({ userId: req.user.id }).sort({ createdAt: -1 });
    res.json({
      success: true,
      count: trips.length,
      data: trips
    });
  } catch (err) {
    console.error("❌ Error fetching trips:", err);
    res.status(500).json({ error: "Failed to fetch trips" });
  }
};
